Use TechShop
--1. Write an SQL query to retrieve a list of all orders along with customer information (e.g., customer name) for each order.
Select Orders.OrderID, Orders.OrderDate, Orders.TotalAmount, Orders.Status, Customers.FirstName, Customers.LastName
From Orders
join Customers ON Orders.CustomerID=Customers.CustomerID

--2. Write an SQL query to find the total revenue generated by each electronic gadget product. Include the product name and the total revenue.
Select Products.ProductName, sum(Products.Price * OrderDetails.Quantity) as TotalRevenue
from OrderDetails
join Products on OrderDetails.ProductID=Products.ProductID
group by Products.ProductName

-- 3. Write an SQL query to list all customers who have made at least one purchase. Include their names and contact information.
Select Distinct CONCAT(Customers.FirstName, Customers.LastName) as CustomerName, Customers.Email, Customers.Phone
from Customers
join Orders on Customers.CustomerID=Orders.CustomerID

-- 4. Write an SQL query to find the most popular electronic gadget, which is the one with the highest total quantity ordered. Include the product name and the total quantity ordered.
Select Top 1 Products.ProductName, sum(OrderDetails.Quantity) as TotalOrderedQuantity
from OrderDetails
join Products on OrderDetails.ProductID=Products.ProductID
Group by Products.ProductName
Order by TotalOrderedQuantity DESC

-- 5. Write an SQL query to retrieve a list of electronic gadgets along with their corresponding categories.
Select ProductName, Description as Category
from Products

-- 6. Write an SQL query to calculate the average order value for each customer. Include the customer's name and their average order value.
Select Concat(Customers.FirstName, Customers.LastName) as CustomerName, avg(Orders.TotalAmount) as AverageOrderValue
from Orders
join Customers on Orders.CustomerID=Customers.CustomerID
Group by Customers.CustomerID,Customers.FirstName,Customers.LastName

-- 7. Write an SQL query to find the order with the highest total revenue. Include the order ID, customer information, and the total revenue.
Select Top 1 Orders.OrderID, concat(Customers.FirstName,' ', Customers.LastName) as CustomerName, Orders.TotalAmount as TotalRevenue
from Orders
join Customers on Orders.CustomerID=Customers.CustomerID
Order by Orders.TotalAmount DESC

-- 8. Write an SQL query to list electronic gadgets and the number of times each product has been ordered.
Select Products.ProductName, Count(OrderDetails.Quantity) as NumberOfOrders
from OrderDetails
join Products on OrderDetails.ProductID=Products.ProductID
group by Products.ProductName

-- 9. Write an SQL query to find customers who have purchased a specific electronic gadget product. Allow users to input the product name as a parameter.
Select Distinct concat(Customers.FirstName, Customers.LastName) as CustomerName, Products.ProductName
from Customers
join Orders on Customers.CustomerID=Orders.CustomerID
join OrderDetails on Orders.OrderID=OrderDetails.OrderID
join Products on OrderDetails.ProductID=Products.ProductID
where Products.ProductName='Keyboard'

--10. Write an SQL query to calculate the total revenue generated by all orders placed within a specific time period. Allow users to input the start and end dates as parameters.
Select sum(Orders.TotalAmount) as TotalRevenue, Count(Orders.OrderID) as NumberOfOrders
from Orders
where Orders.OrderDate Between '2024-09-28' and '2024-10-12'