Use TechShop
-- 1. Write an SQL query to find out which customers have not placed any orders.
Select Customers.CustomerID, concat(Customers.FirstName, Customers.LastName) as CustomerName
from Customers
where Customers.CustomerID Not In (Select Distinct CustomerID from Orders)

-- 2. Write an SQL query to find the total number of products available for sale. 
select (select count(*) from Products) as TotalProductsAvailable

-- 3. Write an SQL query to calculate the total revenue generated by TechShop. 
Select (Select sum(TotalAmount) from Orders) as TotalRevenue

-- 4. Write an SQL query to calculate the average quantity ordered for products in a specific category. Allow users to input the category name as a parameter
select (select avg(Quantity) from OrderDetails where ProductID in (Select ProductID from Products where Description='Flagship Killer'))
as AverageQuantityOrdered

-- 5. Write an SQL query to calculate the total revenue generated by a specific customer. Allow users to input the customer ID as a parameter.
Select (Select Sum(TotalAmount) from Orders where CustomerID=5) as TotalRevenue

-- 6. Write an SQL query to find the customers who have placed the most orders. List their names and the number of orders they've placed.
Select * from Customers Where CustomerID IN(
Select CustomerID from Orders group by CustomerID
Having Count(OrderID)=(Select Max(OrderCount) from (
	select count(OrderID) as OrderCount from Orders
	group by CustomerID) as OrderCounts ))

-- 7. Write an SQL query to find the most popular product category, which is the one with the highest total quantity ordered across all orders
Select Description from Products
where ProductID = (Select Top 1 ProductID from OrderDetails group by ProductID order by sum(Quantity) DESC)

-- 8. Write an SQL query to find the customer who has spent the most money (highest total revenue) on electronic gadgets. List their name and total spending.Select concat(Customers.FirstName, Customers.LastName) as CustomerName from Customers where CustomerID=(Select Top 1 CustomerID from Orders where OrderID in (Select OrderID from OrderDetails where ProductID in (Select ProductID from Products where ProductName='Laptop'))group by CustomerID order by sum(TotalAmount) DESC)

-- 9. Write an SQL query to calculate the average order value (total revenue divided by the number of orders) for all customers.
select(select sum(TotalAmount) / count(*) from Orders) as AverageOrderValue

-- 10. Write an SQL query to find the total number of orders placed by each customer and list their names along with the order count.
select CustomerID, concat(Customers.FirstName, Customers.LastName) as CustomerName, (Select count(*) from Orders where Orders.CustomerID=Customers.CustomerID) as OrderCount
from Customers

select * from Orders
select * from OrderDetails
